### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by onebitme** [bengibaykal/swe573#2]
Wiki data API usage will be explained.

**Comment by bengibaykal** [comment]
Internet, Web, HTML, XML,

Hypertext : Linked document.
https://home.cern/science/computing/birth-web/short-history-web

https://www.w3.org/wiki/InternetRelayChat

**Comment by bengibaykal** [comment]
Sequence diagram : Flow of the data within the system.
Includes: Classes, methods, use case scenarios.
For example : Data type creation sequence diagram.
Each use case has a different sequence diagram and flow.
Ignore GUI components, just abstract design.
 ->data type -> object1 -> object2 -> object3 
------------> method or class and their arguments

actor : wiki data api for example is not my object within my system it is an only useful component for me.
However, I have classes and objects produced from them, so I need to explain one use case as a data flow by using the objects and my data responses.

**Comment by bengibaykal** [comment]
The deliverables 
1. First analysis of requirements
https://github.com/bengibaykal/swe573/wiki/0.-Requirements-Analysis

2. Updated requirements analysis
https://github.com/bengibaykal/swe573/wiki/1.-Software-Requirements

3. Mockups
https://github.com/bengibaykal/swe573/wiki/2.-Mockups
